"use client";

import { useCallback, useEffect, useState } from "react";
import "./alert-history.css";

type Alert={id:string;recipient:string;channel:string;delivery_type:string;highest_severity?:string|null;status:string;attempts:number;item_count:number;suppressed_count:number;created_at:string;sent_at?:string|null;last_error?:string|null};
type Filters={status:string;severity:string;recipient:string;from:string;to:string;page:string};
const initial:Filters={status:"all",severity:"all",recipient:"",from:"",to:"",page:"1"};
async function request(url:string){const response=await fetch(url);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"request_failed");return body;}
const format=(value:string,zone:string)=>new Intl.DateTimeFormat("th-TH",{timeZone:zone,dateStyle:"short",timeStyle:"short",hour12:false}).format(new Date(value));

export default function AlertHistory(){
  const[filters,setFilters]=useState(initial);const[alerts,setAlerts]=useState<Alert[]>([]);const[kpis,setKpis]=useState({pending:0,sent:0,failed:0});const[pagination,setPagination]=useState({page:1,total:0,totalPages:1});const[zone,setZone]=useState("Asia/Bangkok");const[phase,setPhase]=useState("loading");const[error,setError]=useState("");
  useEffect(()=>{const params=new URLSearchParams(location.search);queueMicrotask(()=>setFilters(Object.fromEntries(Object.keys(initial).map(key=>[key,params.get(key)||initial[key as keyof Filters]])) as Filters));},[]);
  const load=useCallback(async()=>{try{const params=new URLSearchParams(Object.entries(filters).filter(([,value])=>value&&value!=="all"));const[data,settings]=await Promise.all([request(`/api/v1/alerts?${params}`),request("/api/v1/settings")]);setAlerts(data.alerts);setKpis(data.kpis);setPagination(data.pagination);setZone(settings.settings?.timezone||"Asia/Bangkok");setPhase("ready");}catch(reason){setError(reason instanceof Error?reason.message:"request_failed");setPhase("error");}},[filters]);
  useEffect(()=>{const timer=window.setTimeout(load,150);return()=>window.clearTimeout(timer);},[load]);
  const update=(patch:Partial<Filters>)=>{const next={...filters,...patch};setFilters(next);const params=new URLSearchParams(Object.entries(next).filter(([,value])=>value&&value!=="all"));history.replaceState(null,"",`/app/alerts?${params}`);};
  return <main className="incident-detail-page"><header className="incident-detail-top"><a href="/app">← กลับ Dashboard</a><div><strong>Alert History</strong><span className="status-chip">{pagination.total} รายการ</span></div></header><section className="incident-hero"><div><p className="console-kicker">NOTIFICATION OPERATIONS</p><h1>ประวัติการแจ้งเตือน</h1><p>ตรวจสอบอีเมลแบบกลุ่ม ผลการส่ง และรายการที่ต้อง Retry</p></div></section>
    <section className="alert-kpis"><article><span>Pending · 24 ชั่วโมง</span><strong>{kpis.pending}</strong></article><article className="sent"><span>Sent · 24 ชั่วโมง</span><strong>{kpis.sent}</strong></article><article className="failed"><span>Failed · 24 ชั่วโมง</span><strong>{kpis.failed}</strong></article></section>
    <section className="console-panel detail-section"><div className="incident-list-filters"><label>Status<select value={filters.status} onChange={event=>update({status:event.target.value,page:"1"})}><option value="all">ทั้งหมด</option><option value="pending">Pending</option><option value="sending">Sending</option><option value="sent">Sent</option><option value="failed">Failed</option></select></label><label>Severity<select value={filters.severity} onChange={event=>update({severity:event.target.value,page:"1"})}><option value="all">ทั้งหมด</option><option>Critical</option><option>High</option><option>Medium</option></select></label><label>ผู้รับ<input value={filters.recipient} onChange={event=>update({recipient:event.target.value,page:"1"})} placeholder="security@example.com"/></label><label>จากวันที่<input type="datetime-local" value={filters.from} onChange={event=>update({from:event.target.value,page:"1"})}/></label><label>ถึงวันที่<input type="datetime-local" value={filters.to} onChange={event=>update({to:event.target.value,page:"1"})}/></label></div></section>
    {error&&<div className="action-notice error">{error}</div>}<section className="console-panel detail-section"><div className="table-wrap"><table><thead><tr><th>เวลา</th><th>ประเภท</th><th>Severity</th><th>ผู้รับ</th><th>Incident</th><th>Attempts</th><th>สถานะ</th><th/></tr></thead><tbody>{alerts.map(alert=><tr key={alert.id}><td>{format(alert.created_at,zone)}</td><td>{alert.delivery_type}</td><td>{alert.highest_severity||"—"}</td><td>{alert.recipient}</td><td>{alert.item_count}<small>ระงับซ้ำ {alert.suppressed_count}</small></td><td>{alert.attempts}</td><td><span className={`alert-status ${alert.status}`}>{alert.status}</span></td><td><a className="detail-button" href={`/app/alerts/${alert.id}?returnTo=${encodeURIComponent(location.pathname+location.search)}`}>รายละเอียด</a></td></tr>)}</tbody></table>{phase==="loading"&&<div className="empty-state">กำลังโหลด…</div>}{phase==="ready"&&!alerts.length&&<div className="empty-state">ยังไม่มีประวัติการแจ้งเตือน</div>}</div><div className="incident-pagination"><button disabled={pagination.page<=1} onClick={()=>update({page:String(pagination.page-1)})}>ก่อนหน้า</button><span>หน้า {pagination.page} / {Math.max(1,pagination.totalPages)}</span><button disabled={pagination.page>=pagination.totalPages} onClick={()=>update({page:String(pagination.page+1)})}>ถัดไป</button></div></section>
  </main>;
}
