"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import "./alert-history.css";

type Delivery={id:string;recipient:string;delivery_type:string;highest_severity?:string;status:string;attempts:number;item_count:number;suppressed_count:number;window_start?:string;window_end?:string;created_at:string;sent_at?:string;last_error?:string;subject?:string};
type Item={id:number;incident_id?:string|null;severity:string;summary:Record<string,unknown>};type Attempt={id:number;attempt_no:number;status:string;error?:string;started_at:string;completed_at?:string};
async function request(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{...(init?.body?{"Content-Type":"application/json"}:{}),...(init?.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"request_failed");return body;}
const format=(value:string,zone:string)=>new Intl.DateTimeFormat("th-TH",{timeZone:zone,dateStyle:"medium",timeStyle:"medium",hour12:false}).format(new Date(value));

export default function AlertDetail(){
  const[id,setId]=useState("");const[delivery,setDelivery]=useState<Delivery|null>(null);const[items,setItems]=useState<Item[]>([]);const[attempts,setAttempts]=useState<Attempt[]>([]);const[role,setRole]=useState("");const[csrf,setCsrf]=useState("");const[zone,setZone]=useState("Asia/Bangkok");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(async(alertId:string)=>{try{const[auth,data,settings]=await Promise.all([request("/api/v1/auth/me"),request(`/api/v1/alerts/${alertId}`),request("/api/v1/settings")]);setRole(auth.user.role);setCsrf(auth.csrfToken);setDelivery(data.alert);setItems(data.items);setAttempts(data.attempts);setZone(settings.settings?.timezone||"Asia/Bangkok");}catch(reason){setError(reason instanceof Error?reason.message:"request_failed");}},[]);
  useEffect(()=>{const alertId=location.pathname.split("/").filter(Boolean).at(-1)||"";queueMicrotask(()=>{setId(alertId);load(alertId);});},[load]);
  const back=useMemo(()=>{const value=new URLSearchParams(typeof location==="undefined"?"":location.search).get("returnTo");return value?.startsWith("/app/alerts")?value:"/app/alerts";},[]);
  const retry=async()=>{setBusy(true);setError("");try{await request(`/api/v1/alerts/${id}/retry`,{method:"POST",headers:{"x-csrf-token":csrf}});await load(id);}catch(reason){setError(reason instanceof Error?reason.message:"request_failed");}finally{setBusy(false);}};
  if(!delivery)return <main className="incident-detail-state"><h1>{error||"กำลังโหลด Alert…"}</h1><Link href="/app/alerts">กลับ Alert History</Link></main>;
  return <main className="incident-detail-page"><header className="incident-detail-top"><a href={back}>← กลับ Alert History</a><div><strong>{delivery.delivery_type.toUpperCase()}</strong><span className={`alert-status ${delivery.status}`}>{delivery.status}</span></div></header><section className="incident-hero"><div><p className="console-kicker">ALERT DELIVERY</p><h1>{delivery.subject||"Summary Log AI alert"}</h1><p>{delivery.recipient} · {delivery.item_count} Incident · ระงับซ้ำ {delivery.suppressed_count}</p></div><dl><div><dt>สร้างเมื่อ</dt><dd>{format(delivery.created_at,zone)}</dd></div>{delivery.sent_at&&<div><dt>ส่งสำเร็จ</dt><dd>{format(delivery.sent_at,zone)}</dd></div>}<div><dt>Attempts</dt><dd>{delivery.attempts}</dd></div></dl></section>{error&&<div className="action-notice error">{error}</div>}
    <div className="incident-detail-grid"><div className="incident-detail-main"><section className="console-panel detail-section"><h2>เหตุการณ์ในอีเมล</h2><div className="alert-items">{items.map(item=>{const row=item.summary;return <article className="alert-item" key={item.id}><span className={`severity severity-${item.severity.toLowerCase()}`}>{item.severity}</span><div><strong>{String(row.source||"Source")} · {String(row.srcIp||"?")} → {String(row.dstIp||"?")}:{String(row.dstPort||"?")}</strong><p>Score {String(row.score||0)} · {Array.isArray(row.ruleCodes)?row.ruleCodes.join(", "):"Legacy alert"}</p></div>{item.incident_id&&<a href={`/app/incidents/${item.incident_id}`}>เปิด Incident</a>}</article>})}{!items.length&&<div className="empty-state">Test Email ไม่มี Incident</div>}</div></section></div><aside className="incident-detail-side"><section className="console-panel detail-section"><h2>สถานะการส่ง</h2>{delivery.last_error&&<p className="alert-error">{delivery.last_error}</p>}{role==="admin"&&delivery.status==="failed"&&<button className="primary-action full" disabled={busy} onClick={retry}>{busy?"กำลังเข้าคิว…":"Retry Email"}</button>}</section><section className="console-panel detail-section"><h2>Attempt History</h2><div className="alert-attempts">{attempts.map(attempt=><article key={attempt.id}><strong>ครั้งที่ {attempt.attempt_no} · {attempt.status}</strong><small>{format(attempt.started_at,zone)}</small>{attempt.error&&<p>{attempt.error}</p>}</article>)}{!attempts.length&&<div className="empty-state">ยังไม่มีการพยายามส่ง</div>}</div></section></aside></div>
  </main>;
}
