"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Incident={id:string;source_name:string;src_ip:string;dst_ip:string;dst_port:number;protocol:string;score:number;severity:string;status:string;assignee_name?:string;first_seen_at:string;last_seen_at:string;occurrence_count:number};
type Option={id:string;name?:string;display_name?:string;role?:string};
type Filters={ip:string;status:string;severity:string;sourceId:string;assigneeId:string;from:string;to:string;sort:string;order:string;page:string};
const initial:Filters={ip:"",status:"all",severity:"all",sourceId:"",assigneeId:"",from:"",to:"",sort:"severity",order:"desc",page:"1"};
const nf=new Intl.NumberFormat("th-TH");
const statusText:Record<string,string>={new:"New",acknowledged:"Acknowledged",investigating:"Investigating",resolved:"Resolved"};
async function request(url:string){const r=await fetch(url);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"request_failed");return b;}
const format=(value:string,zone:string)=>new Intl.DateTimeFormat("th-TH",{timeZone:zone,dateStyle:"short",timeStyle:"short",hour12:false}).format(new Date(value));

export default function IncidentList(){
  const[filters,setFilters]=useState(initial);const[rows,setRows]=useState<Incident[]>([]);const[sources,setSources]=useState<Option[]>([]);const[assignees,setAssignees]=useState<Option[]>([]);const[zone,setZone]=useState("Asia/Bangkok");const[pageInfo,setPageInfo]=useState({page:1,total:0,totalPages:1});const[phase,setPhase]=useState<"loading"|"ready"|"error"|"unauthorized">("loading");const[error,setError]=useState("");
  useEffect(()=>{const q=new URLSearchParams(location.search);queueMicrotask(()=>setFilters(Object.fromEntries(Object.keys(initial).map(k=>[k,q.get(k)||initial[k as keyof Filters]])) as Filters));},[]);
  const load=useCallback(async()=>{try{const params=new URLSearchParams(Object.entries(filters).filter(([,v])=>v&&v!=="all"));const[list,sourceData,userData,settings]=await Promise.all([request(`/api/v1/incidents?${params}`),request("/api/v1/sources"),request("/api/v1/users"),request("/api/v1/settings")]);setRows(list.incidents);setPageInfo(list.pagination);setSources(sourceData.sources||[]);setAssignees((userData.users||[]).filter((u:Option)=>["admin","analyst"].includes(u.role||"")));setZone(settings.settings?.timezone||"Asia/Bangkok");setPhase("ready");}catch(e){const message=e instanceof Error?e.message:"request_failed";setError(message);setPhase(message==="authentication_required"?"unauthorized":"error");}},[filters]);
  useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer);},[load]);
  const update=(patch:Partial<Filters>)=>{const next={...filters,...patch};setFilters(next);const params=new URLSearchParams(Object.entries(next).filter(([,v])=>v&&v!=="all"));history.replaceState(null,"",`/app/incidents?${params}`);};
  const submit=(e:FormEvent)=>{e.preventDefault();update({page:"1"});};
  if(phase==="unauthorized")return <main className="incident-detail-state"><h1>กรุณาเข้าสู่ระบบ</h1><a href="/app">ไปหน้าเข้าสู่ระบบ</a></main>;
  return <main className="incident-detail-page"><header className="incident-detail-top"><a href="/app">← กลับ Dashboard</a><div><strong>Incident Management</strong><span className="status-chip">{nf.format(pageInfo.total)} รายการ</span></div></header><section className="incident-hero"><div><p className="console-kicker">SECURITY OPERATIONS</p><h1>ตรวจสอบและติดตาม Incident</h1><p>ค้นหา กรอง เรียงลำดับ และเปิดดูหลักฐานของแต่ละเหตุการณ์</p></div></section>
    <section className="console-panel detail-section"><form className="incident-list-filters" onSubmit={submit}><label>ค้นหา IP<input value={filters.ip} onChange={e=>update({ip:e.target.value,page:"1"})} placeholder="Source หรือ Destination IP"/></label><label>Status<select value={filters.status} onChange={e=>update({status:e.target.value,page:"1"})}><option value="all">ทั้งหมด</option>{Object.entries(statusText).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Severity<select value={filters.severity} onChange={e=>update({severity:e.target.value,page:"1"})}><option value="all">ทั้งหมด</option><option>Critical</option><option>High</option><option>Medium</option></select></label><label>Source<select value={filters.sourceId} onChange={e=>update({sourceId:e.target.value,page:"1"})}><option value="">ทุก Source</option>{sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>ผู้รับผิดชอบ<select value={filters.assigneeId} onChange={e=>update({assigneeId:e.target.value,page:"1"})}><option value="">ทั้งหมด</option><option value="unassigned">ยังไม่มอบหมาย</option>{assignees.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label><label>จากวันที่<input type="datetime-local" value={filters.from} onChange={e=>update({from:e.target.value,page:"1"})}/></label><label>ถึงวันที่<input type="datetime-local" value={filters.to} onChange={e=>update({to:e.target.value,page:"1"})}/></label><label>เรียงตาม<select value={filters.sort} onChange={e=>update({sort:e.target.value,page:"1"})}><option value="severity">Severity</option><option value="lastSeen">เวลาล่าสุด</option><option value="firstSeen">เวลาเริ่ม</option><option value="source">Source</option><option value="ip">Source IP</option></select></label><label>ลำดับ<select value={filters.order} onChange={e=>update({order:e.target.value,page:"1"})}><option value="desc">มากไปน้อย / ล่าสุด</option><option value="asc">น้อยไปมาก / เก่าสุด</option></select></label></form></section>
    {error&&<div className="action-notice error">{error}</div>}<section className="console-panel detail-section"><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Source / IP</th><th>ปลายทางล่าสุด</th><th>ช่วงเวลา</th><th>Occurrences</th><th>ผู้รับผิดชอบ</th><th>Status</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><span className={`severity severity-${row.severity.toLowerCase()}`}>{row.severity}</span><small>Score {row.score}</small></td><td><strong>{row.source_name}</strong><small>{row.src_ip}</small></td><td>{row.dst_ip}:{row.dst_port}<small>{row.protocol.toUpperCase()}</small></td><td>{format(row.last_seen_at,zone)}<small>เริ่ม {format(row.first_seen_at,zone)}</small></td><td>{nf.format(row.occurrence_count)}</td><td>{row.assignee_name||"ยังไม่มอบหมาย"}</td><td>{statusText[row.status]||row.status}</td><td><a className="detail-button" href={`/app/incidents/${row.id}?returnTo=${encodeURIComponent(location.pathname+location.search)}`}>รายละเอียด</a></td></tr>)}</tbody></table>{phase==="loading"&&<div className="empty-state">กำลังโหลด…</div>}{phase==="ready"&&!rows.length&&<div className="empty-state">ไม่พบ Incident ตามตัวกรองนี้</div>}</div><div className="incident-pagination"><button disabled={pageInfo.page<=1} onClick={()=>update({page:String(pageInfo.page-1)})}>ก่อนหน้า</button><span>หน้า {pageInfo.page} / {Math.max(1,pageInfo.totalPages)}</span><button disabled={pageInfo.page>=pageInfo.totalPages} onClick={()=>update({page:String(pageInfo.page+1)})}>ถัดไป</button></div></section>
  </main>;
}
