"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Incident = { id:string; source_name:string; source_id:string; src_ip:string; dst_ip:string; dst_port:number; protocol:string; score:number; severity:"Medium"|"High"|"Critical"; status:"new"|"acknowledged"|"investigating"|"resolved"; resolution?:string|null; reason:string; suggested_action:string; rule_codes:string[]; assignee_user_id?:string|null; assignee_name?:string|null; first_seen_at:string; last_seen_at:string; occurrence_count:number; suppressed_count:number; last_suppressed_at?:string|null };
type Match = { code:string; points:number; label:string; actual:number; threshold:number; unit:string; configuredThreshold?:number; baselineThreshold?:number|null; thresholdSource?:"default"|"source"|"baseline"; cooldownMinutes?:number; suppressed?:boolean };
type Occurrence = { id:string; observed_at:string; src_ip:string; dst_ip:string; dst_port:number; protocol:string; score:number; severity:string; rule_codes:string[]; score_breakdown:Match[]; connection_count:number; destination_count:number; failed_count:number; failed_ratio:number; byte_count:number; packet_count:number; max_duration_ms:number };
type History = { id:number; actor_name?:string; action:string; from_status?:string; to_status:string; note?:string; created_at:string };
type Assignee = { id:string; display_name:string; email:string; role:string };
type Detail = { incident:Incident; occurrences:Occurrence[]; history:History[]; assignees:Assignee[] };

const statusText:Record<string,string>={new:"New",acknowledged:"Acknowledged",investigating:"Investigating",resolved:"Resolved"};
const actionText:Record<string,string>={created:"สร้าง Incident",merged:"รวมเหตุการณ์ซ้ำ",reopened:"เปิด Incident อีกครั้ง",status_changed:"เปลี่ยนสถานะ",assigned:"มอบหมายผู้รับผิดชอบ",note_added:"เพิ่ม Note"};
const nextStatus:Record<string,string|undefined>={new:"acknowledged",acknowledged:"investigating",investigating:"resolved"};
const nf=new Intl.NumberFormat("th-TH");
const format=(value:string,zone:string)=>new Intl.DateTimeFormat("th-TH",{timeZone:zone,dateStyle:"medium",timeStyle:"medium",hour12:false}).format(new Date(value));
const bytes=(n=0)=>n>=1e9?`${(n/1e9).toFixed(2)} GB`:n>=1e6?`${(n/1e6).toFixed(1)} MB`:n>=1e3?`${(n/1e3).toFixed(1)} KB`:`${n} B`;
const actual=(match:Match)=>match.unit==="bytes"?bytes(match.actual):match.unit==="ms"?`${(match.actual/1000).toFixed(1)} s`:`${nf.format(match.actual)} ${match.unit}`;
async function request(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{...(init?.body?{"Content-Type":"application/json"}:{}),...(init?.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"request_failed");return body;}

export default function IncidentDetail(){
  const[id,setId]=useState("");const[data,setData]=useState<Detail|null>(null);const[csrf,setCsrf]=useState("");const[role,setRole]=useState("");const[zone,setZone]=useState("Asia/Bangkok");
  const[phase,setPhase]=useState<"loading"|"ready"|"not-found"|"unauthorized"|"error">("loading");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[note,setNote]=useState("");const[resolution,setResolution]=useState("true_positive");
  const load=useCallback(async(incidentId:string)=>{try{const[auth,settings,detail]=await Promise.all([request("/api/v1/auth/me"),request("/api/v1/settings"),request(`/api/v1/incidents/${incidentId}`)]);setCsrf(auth.csrfToken);setRole(auth.user.role);setZone(settings.settings?.timezone||"Asia/Bangkok");if(detail.incident.suppressed_count)detail.incident.source_name+=` · Suppressed ${detail.incident.suppressed_count}${detail.incident.last_suppressed_at?` · ล่าสุด ${format(detail.incident.last_suppressed_at,settings.settings?.timezone||"Asia/Bangkok")}`:""}`;setData(detail);setPhase("ready");}catch(e){const message=e instanceof Error?e.message:"request_failed";setPhase(message==="incident_not_found"?"not-found":message==="authentication_required"?"unauthorized":"error");setError(message);}},[]);
  useEffect(()=>{const incidentId=location.pathname.split("/").filter(Boolean).at(-1)||"";queueMicrotask(()=>{setId(incidentId);load(incidentId);});},[load]);
  const mutate=async(url:string,method:string,body:unknown)=>{setBusy(true);setError("");try{await request(url,{method,headers:{"x-csrf-token":csrf},body:JSON.stringify(body)});await load(id);}catch(e){setError(e instanceof Error?e.message:"request_failed");}finally{setBusy(false);}};
  const back=useMemo(()=>{const value=new URLSearchParams(typeof location==="undefined"?"":location.search).get("returnTo");return value?.startsWith("/app")?value:"/app?tab=incidents";},[]);
  if(phase==="loading")return <main className="incident-detail-state">กำลังโหลด Incident…</main>;
  if(phase!=="ready"||!data)return <main className="incident-detail-state"><h1>{phase==="not-found"?"ไม่พบ Incident":phase==="unauthorized"?"กรุณาเข้าสู่ระบบ":"เปิด Incident ไม่สำเร็จ"}</h1><p>{error}</p><a href="/app">กลับไป Dashboard</a></main>;
  const {incident,occurrences,history,assignees}=data;const latest=occurrences[0];const matches=(latest?.score_breakdown||[]).map(match=>({...match,label:`${match.label} · ${match.thresholdSource||"legacy"}${match.suppressed?" · suppressed":""}`}));const next=nextStatus[incident.status];const canWrite=role!=="viewer";const isAdmin=role==="admin";
  return <main className="incident-detail-page"><header className="incident-detail-top"><a href={back}>← กลับไป Incident list</a><div><span className={`severity severity-${incident.severity.toLowerCase()}`}>{incident.severity}</span><strong>{incident.score}/100</strong><span className="status-chip">{statusText[incident.status]}</span></div></header>
    <section className="incident-hero"><div><p className="console-kicker">INCIDENT DETAIL</p><h1>{incident.src_ip} <span>→</span> {incident.dst_ip}:{incident.dst_port}</h1><p>{incident.source_name} · {incident.protocol.toUpperCase()} · รวม {nf.format(incident.occurrence_count)} ครั้ง</p></div><dl><div><dt>พบครั้งแรก</dt><dd>{format(incident.first_seen_at,zone)}</dd></div><div><dt>พบล่าสุด</dt><dd>{format(incident.last_seen_at,zone)}</dd></div><div><dt>ผู้รับผิดชอบ</dt><dd>{incident.assignee_name||"ยังไม่มอบหมาย"}</dd></div></dl></section>
    {error&&<div className="action-notice error">{error}</div>}<div className="incident-detail-grid"><div className="incident-detail-main">
      <section className="console-panel detail-section"><h2>เหตุผลและ Score breakdown</h2><p>{incident.reason}</p><div className="score-breakdown">{matches.map(match=><article key={match.code}><div><strong>{match.label}</strong><span>+{match.points}</span></div><code>{match.code}</code><p>ตรวจพบ <b>{actual(match)}</b> · เกณฑ์ {match.threshold?actual({...match,actual:match.threshold}):"พอร์ตนอกมาตรฐาน"}</p></article>)}{!matches.length&&<p>Incident เดิมยังไม่มีรายละเอียดคะแนนรายกฎ</p>}</div></section>
      <section className="console-panel detail-section"><h2>Evidence summary</h2>{latest?<div className="detail-evidence"><div><span>Connections</span><strong>{nf.format(latest.connection_count)}</strong></div><div><span>Destinations</span><strong>{nf.format(latest.destination_count)}</strong></div><div><span>Failed ratio</span><strong>{(latest.failed_ratio*100).toFixed(1)}%</strong></div><div><span>Transfer</span><strong>{bytes(latest.byte_count)}</strong></div><div><span>Packets</span><strong>{nf.format(latest.packet_count)}</strong></div><div><span>Max duration</span><strong>{(latest.max_duration_ms/1000).toFixed(1)} s</strong></div></div>:<p>ยังไม่มีหลักฐานสรุป</p>}<small className="privacy-caption">เก็บเฉพาะค่าที่ใช้ตัดสิน ไม่เก็บ Raw Zeek Log</small></section>
      <section className="console-panel detail-section"><h2>Occurrence timeline</h2><div className="occurrence-list">{occurrences.map((row,index)=><article key={row.id}><i/><div><strong>#{occurrences.length-index} · {row.src_ip} → {row.dst_ip}:{row.dst_port}/{row.protocol}</strong><p>{row.severity} · Score {row.score} · {row.rule_codes?.join(", ")}</p><small>{format(row.observed_at,zone)}</small></div></article>)}</div></section>
    </div><aside className="incident-detail-side"><section className="console-panel detail-section"><h2>ดำเนินการ</h2>{isAdmin&&<label>ผู้รับผิดชอบ<select value={incident.assignee_user_id||""} disabled={busy} onChange={e=>mutate(`/api/v1/incidents/${id}/assignee`,"PATCH",{assigneeUserId:e.target.value||null})}><option value="">ยังไม่มอบหมาย</option>{assignees.map(x=><option key={x.id} value={x.id}>{x.display_name} ({x.role})</option>)}</select></label>}{canWrite&&next&&<>{next==="resolved"&&<label>Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option value="true_positive">True Positive</option><option value="false_positive">False Positive</option><option value="benign">Benign</option></select></label>}<button className="primary-action full" disabled={busy} onClick={()=>mutate(`/api/v1/incidents/${id}`,"PATCH",{status:next,resolution:next==="resolved"?resolution:null})}>{next==="acknowledged"?"รับทราบ Incident":next==="investigating"?"เริ่มตรวจสอบ":"ปิด Incident"}</button></>}{!canWrite&&<p>Viewer สามารถอ่านข้อมูลได้อย่างเดียว</p>}{canWrite&&<form onSubmit={(e:FormEvent)=>{e.preventDefault();if(note.trim())mutate(`/api/v1/incidents/${id}/notes`,"POST",{note}).then(()=>setNote(""));}}><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="บันทึกสิ่งที่ตรวจสอบ…"/></label><button className="secondary-action full" disabled={busy||!note.trim()}>เพิ่ม Note</button></form>}</section>
      <section className="console-panel detail-section"><h2>แนวทางตรวจสอบ</h2><p>{incident.suggested_action}</p></section><section className="console-panel detail-section"><h2>History</h2><div className="history-list">{history.map(row=><div key={row.id}><i/><div><strong>{row.actor_name||"ระบบ"} · {actionText[row.action]||row.action}</strong>{row.note&&<p>{row.note}</p>}<small>{format(row.created_at,zone)}</small></div></div>)}</div></section></aside></div>
  </main>;
}
