"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import "./rule-management.css";

type Threshold={minimum?:number;count?:number;ratio?:number;ports?:number[]};
type Definition={code:string;enabled:boolean;points:number;cooldownMinutes:number;threshold:Threshold;label:string;description:string};
type Config={source_id:string|null;rule_code:string;enabled:boolean;points:number;cooldown_minutes:number;threshold:Threshold};
type Baseline={source_id:string;hour_of_day:number;rule_code:string;sample_count:number;day_count:number;suggested_threshold:number;status:string;computed_at:string};
type Source={id:string;name:string};
type Data={definitions:Definition[];configs:Config[];sources:Source[];baselines:Baseline[];rebuilds:Array<{source_id:string;status:string}>};
const empty:Data={definitions:[],configs:[],sources:[],baselines:[],rebuilds:[]};
async function api(url:string,init?:RequestInit){const r=await fetch(url,{...init,headers:{...(init?.body?{"Content-Type":"application/json"}:{}),...(init?.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"request_failed");return b;}
const displayValue=(code:string,value:number)=>["HIGH_TRANSFER_VOLUME","LARGE_SINGLE_FLOW"].includes(code)?value/1024/1024:code==="LONG_CONNECTION"?value/1000:value;
const storageValue=(code:string,value:number)=>["HIGH_TRANSFER_VOLUME","LARGE_SINGLE_FLOW"].includes(code)?value*1024*1024:code==="LONG_CONNECTION"?value*1000:value;
const unit=(code:string)=>["HIGH_TRANSFER_VOLUME","LARGE_SINGLE_FLOW"].includes(code)?"MB":code==="LONG_CONNECTION"?"วินาที":code==="INCIDENT_THRESHOLD"?"คะแนน":"ครั้ง";

export default function RuleManagement(){
  const[data,setData]=useState(empty);const[scope,setScope]=useState("default");const[role,setRole]=useState("");const[csrf,setCsrf]=useState("");const[zone,setZone]=useState("Asia/Bangkok");const[phase,setPhase]=useState("loading");const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{const[auth,rules,settings]=await Promise.all([api("/api/v1/auth/me"),api("/api/v1/rules"),api("/api/v1/settings")]);setRole(auth.user.role);setCsrf(auth.csrfToken);setData(rules);setZone(settings.settings?.timezone||"Asia/Bangkok");setPhase("ready");}catch(e){setNotice(e instanceof Error?e.message:"request_failed");setPhase("error");}},[]);
  useEffect(()=>{queueMicrotask(load);},[load]);
  const hour=useMemo(()=>Number(new Intl.DateTimeFormat("en-US",{timeZone:zone,hour:"2-digit",hourCycle:"h23"}).format(new Date())),[zone]);
  const defaults=useMemo(()=>new Map(data.configs.filter(x=>!x.source_id).map(x=>[x.rule_code,x])),[data]);const overrides=useMemo(()=>new Map(data.configs.filter(x=>x.source_id===scope).map(x=>[x.rule_code,x])),[data,scope]);
  const mutate=async(url:string,method:string,body?:unknown)=>{setNotice("");try{await api(url,{method,headers:{"x-csrf-token":csrf},body:body===undefined?undefined:JSON.stringify(body)});setNotice("บันทึกเรียบร้อย");await load();}catch(e){setNotice(e instanceof Error?e.message:"request_failed");}};
  if(phase!=="ready")return <main className="incident-detail-state"><h1>{phase==="loading"?"กำลังโหลดกฎ…":"เปิด Rule Management ไม่สำเร็จ"}</h1><p>{notice}</p><a href="/app">กลับ Dashboard</a></main>;
  return <main className="incident-detail-page"><header className="incident-detail-top"><a href="/app">← กลับ Dashboard</a><div><strong>Rule Management</strong><span className="status-chip">{role==="admin"?"Admin":"Read only"}</span></div></header><section className="incident-hero"><div><p className="console-kicker">FALSE POSITIVE CONTROL</p><h1>ปรับกฎให้เหมาะกับแต่ละเครือข่าย</h1><p>Threshold ที่ใช้จริงจะไม่ต่ำกว่าค่า Admin และ Baseline เพิ่มได้สูงสุด 4 เท่า</p></div><label className="scope-picker">Rule scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="default">Organization defaults</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></section>
    {notice&&<div className="action-notice success">{notice}</div>}{scope!=="default"&&<section className="baseline-banner"><div><span>BASELINE · ชั่วโมง {String(hour).padStart(2,"0")}:00</span><strong>{data.rebuilds.find(x=>x.source_id===scope)?.status||"automatic"}</strong></div>{role==="admin"&&<button onClick={()=>mutate(`/api/v1/sources/${scope}/baseline/rebuild`,"POST",{})}>Rebuild Baseline</button>}</section>}
    <section className="rule-admin-grid">{data.definitions.map(def=>{const base=defaults.get(def.code)||def;const override=overrides.get(def.code);const current=(scope==="default"?base:override||base) as Definition|Config;const baseline=data.baselines.find(x=>x.source_id===scope&&x.hour_of_day===hour&&x.rule_code===def.code);return <RuleEditor key={`${scope}-${def.code}`} definition={def} current={current} baseline={baseline} inherited={scope!=="default"&&!override} canEdit={role==="admin"} save={body=>mutate(scope==="default"?`/api/v1/rules/defaults/${def.code}`:`/api/v1/sources/${scope}/rules/${def.code}`,"PATCH",body)} reset={scope!=="default"&&override?()=>mutate(`/api/v1/sources/${scope}/rules/${def.code}`,"DELETE"):undefined}/>})}</section>
  </main>;
}

function RuleEditor({definition,current,baseline,inherited,canEdit,save,reset}:{definition:Definition;current:Definition|Config;baseline?:Baseline;inherited:boolean;canEdit:boolean;save:(body:unknown)=>void;reset?:()=>void}){
  const[enabled,setEnabled]=useState(current.enabled);const[points,setPoints]=useState(current.points);const[cooldown,setCooldown]=useState("cooldown_minutes" in current?current.cooldown_minutes:current.cooldownMinutes);const threshold=current.threshold;const[minimum,setMinimum]=useState(displayValue(definition.code,Number(threshold.minimum??threshold.count??0)));const[ratio,setRatio]=useState(Number(threshold.ratio??.5)*100);const[ports,setPorts]=useState((threshold.ports||[]).join(", "));
  const baselineValue=baseline?displayValue(definition.code,Number(baseline.suggested_threshold)):null;const effective=baseline?.status==="ready"&&baselineValue!==null?Math.min(minimum*4,Math.max(minimum,baselineValue)):minimum;
  const submit=(e:FormEvent)=>{e.preventDefault();const nextThreshold:Threshold=definition.code==="UNCOMMON_PORT"?{ports:ports.split(",").map(x=>Number(x.trim())).filter(Boolean)}:definition.code==="HIGH_FAILURE_RATIO"?{count:storageValue(definition.code,minimum),ratio:ratio/100}:{minimum:storageValue(definition.code,minimum)};const defaultMinimum=displayValue(definition.code,Number(definition.threshold.minimum??definition.threshold.count??0));const noisy=definition.code!=="UNCOMMON_PORT"&&(minimum<defaultMinimum||Number(cooldown)<5||Number(points)>definition.points);if(noisy&&!window.confirm("This setting may create significantly more incidents. Continue?"))return;save({enabled,points:Number(points),cooldownMinutes:Number(cooldown),threshold:nextThreshold});};
  const baselineState=!baseline?"Learning":baseline.status==="stale"?"Stale":baseline.status==="ready"?"Ready":"Insufficient data";
  return <form className={`console-panel rule-editor ${!enabled?"disabled":""}`} onSubmit={submit}><header><div><span>{definition.code}</span><h2>{definition.label}</h2><p>{definition.description}</p></div><label className="toggle"><input type="checkbox" checked={enabled} disabled={!canEdit} onChange={e=>setEnabled(e.target.checked)}/><i/></label></header><div className="rule-source-row"><span>{inherited?"ใช้ Organization default":"Override"}</span>{baseline&&<span className={`baseline-state ${baselineState.toLowerCase().replace(" ","-")}`}>{baselineState} · {baseline.sample_count} samples</span>}</div><div className="rule-fields">{definition.code==="UNCOMMON_PORT"?<label className="wide">Standard ports<input value={ports} disabled={!canEdit} onChange={e=>setPorts(e.target.value)}/></label>:<label>{definition.code==="HIGH_FAILURE_RATIO"?"Failed count":"Admin threshold"}<input type="number" min="0" value={minimum} disabled={!canEdit} onChange={e=>setMinimum(Number(e.target.value))}/><small>{unit(definition.code)}</small></label>}{definition.code==="HIGH_FAILURE_RATIO"&&<label>Failure ratio<input type="number" min="1" max="100" value={ratio} disabled={!canEdit} onChange={e=>setRatio(Number(e.target.value))}/><small>%</small></label>}<label>คะแนน<input type="number" min="0" max="100" value={points} disabled={!canEdit||definition.code==="INCIDENT_THRESHOLD"} onChange={e=>setPoints(Number(e.target.value))}/></label><label>Cooldown<input type="number" min="1" max="1440" value={cooldown} disabled={!canEdit} onChange={e=>setCooldown(Number(e.target.value))}/><small>นาที</small></label></div>{definition.code!=="UNCOMMON_PORT"&&<div className="threshold-summary"><span>Admin <b>{minimum}</b></span><span>Baseline <b>{baselineValue===null?"—":baselineValue.toFixed(1)}</b></span><span>Effective <b>{effective.toFixed(1)} {unit(definition.code)}</b></span></div>}{canEdit&&<footer><button className="primary-action">บันทึกกฎ</button>{reset&&<button type="button" className="danger-link" onClick={reset}>Reset override</button>}</footer>}</form>;
}
